/*
# Allow explicit IDs for seeding

Changes all identity columns from GENERATED ALWAYS to GENERATED BY DEFAULT
so that seed data can insert explicit ID values while still auto-generating
when no ID is provided.
*/

ALTER TABLE categories ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE products ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE delivery_zones ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE deliverers ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE orders ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE order_items ALTER COLUMN id SET GENERATED BY DEFAULT;
